name: .NET CI

on:
  push:
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        dotnet: ['5.0.x', '6.0.x']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    name: .NET ${{ matrix.dotnet }} on ${{ matrix.os }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build PeyrSharp
        run: dotnet build PeyrSharp/PeyrSharp.csproj -c Release

      - name: Build PeyrSharp.Core
        run: dotnet build PeyrSharp.Core/PeyrSharp.Core.csproj -c Release

      - name: Build PeyrSharp.Enums
        run: dotnet build PeyrSharp.Enums/PeyrSharp.Enums.csproj -c Release

      - name: Build PeyrSharp.Exceptions
        run: dotnet build PeyrSharp.Exceptions/PeyrSharp.Exceptions.csproj -c Release
      
      - name: Test PeyrSharp.Core
        run: dotnet test PeyrSharp/PeyrSharp.csproj
